name: Auto Update and Push

on:
  schedule:
    - cron: "0 5 * * *" # Runs daily at 5 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Don't use fetch-depth: 0 - we want a clean checkout

      - name: Make changes
        run: |
          echo "Last updated: $(date)" > last_updated.txt

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Deploy using peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: .
          force_orphan: false
          commit_message: "Automated daily update: $(date)"
