name: Auto Update and Push

on:
  schedule:
    - cron: "0 5 * * *" # Runs daily at midnight UTC

  workflow_dispatch: # Allows manual triggering

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make changes (e.g., pull latest data)
        run: |
          echo "Last updated: $(date)" > last_updated.txt

      - name: Pull latest changes
        run: |
          git pull --rebase origin main

      - name: Commit and Push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git add .
          git commit -m "Automated daily update: $(date)" || echo "No changes to commit"

          # Ensure we are up to date
          git pull --rebase origin main || git rebase --abort  

          # Push the updates
          git push --force origin main
