name: Auto Update and Push

on:
  schedule:
    - cron: "0 5 * * *" # Runs daily at 5 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0 # Ensure full history is available

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make changes (e.g., update timestamp)
        run: |
          echo "Last updated: $(date)" > last_updated.txt

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated daily update: $(date)" || echo "No changes to commit"

      - name: Fetch and merge changes
        run: |
          # Fetch latest changes
          git fetch origin main
          # Merge with strategy to prefer our changes in case of conflicts
          git merge -X ours --no-edit origin/main || git merge --abort

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: false
